import type {
  GenerationRunDetails,
  GeneratedArtifactSummary,
  TreeNode,
} from "@mag/shared";
import { FileTreeViewer } from "./FileTreeViewer";

interface RunDetailsPanelProps {
  details: GenerationRunDetails | null;
  loading: boolean;
  error: string | null;
  language?: "ua" | "en";
  labels?: {
    empty: string;
    loading: string;
    title: string;
    summary: string;
    modules: string;
    metrics: string;
    advanced: string;
    platform?: string;
    mode?: string;
    provider?: string;
    created?: string;
    architecture?: string;
    state?: string;
    navigation?: string;
    zip?: string;
    ready?: string;
    missing?: string;
    files?: string;
    artifacts?: string;
    warnings?: string;
    validation?: string;
    advisorTitle?: string;
    advisorRationale?: string;
    advisorModules?: string;
    advisorMode?: string;
    advisorTradeoffs?: string;
    advisorChecks?: string;
    relationshipEdges?: string;
    aiContribution?: string;
    projectTree?: string;
  };
}

function formatMs(value?: number): string {
  if (typeof value !== "number") return "-";
  return value < 1000 ? `${value} ms` : `${(value / 1000).toFixed(1)} s`;
}

function buildTreeFromArtifacts(details: GenerationRunDetails): TreeNode[] {
  const existingTree = details.metadata.fileTree;
  if (existingTree?.length) {
    return existingTree;
  }

  const paths = details.artifacts
    .map((artifact) => artifact.path)
    .filter((path) => path && !path.endsWith("/"));
  const folders = new Set<string>();
  for (const path of paths) {
    const parts = path.split("/").filter(Boolean);
    for (let index = 1; index < parts.length; index += 1) {
      folders.add(parts.slice(0, index).join("/"));
    }
  }

  return [
    ...Array.from(folders).map((path) => ({
      path,
      type: "directory" as const,
    })),
    ...paths.map((path) => ({ path, type: "file" as const })),
  ].sort((left, right) => {
    if (left.path === right.path) return 0;
    return left.path.localeCompare(right.path);
  });
}

function artifactSummaries(
  details: GenerationRunDetails,
): GeneratedArtifactSummary[] {
  return details.artifacts.map((artifact) => ({
    path: artifact.path,
    kind: artifact.kind,
    description: artifact.description,
  }));
}

function fileTreeLabels(language: "ua" | "en") {
  const ua = language === "ua";
  return {
    title: ua ? "Дерево запуску" : "Run file tree",
    copy: ua ? "Скопіювати дерево" : "Copy tree",
    copied: ua ? "Скопійовано" : "Copied",
    copyPath: ua ? "Копіювати шлях" : "Copy path",
    files: ua ? "Файли" : "Files",
    folders: ua ? "Папки" : "Folders",
    docs: ua ? "Docs" : "Docs",
    metadata: ua ? "Metadata" : "Metadata",
    empty: ua
      ? "У цьому запуску немає дерева файлів."
      : "This run has no file tree.",
    selectedItem: ua ? "Обраний файл" : "Selected item",
    type: ua ? "Тип" : "Type",
    path: ua ? "Шлях" : "Path",
    description: ua ? "Опис" : "Description",
    category: ua ? "Категорія" : "Category",
    extension: ua ? "Розширення" : "Extension",
    generatedBy: ua ? "Згенеровано" : "Generated by",
    children: ua ? "Вміст" : "Children",
    folder: ua ? "Папка" : "Folder",
    file: ua ? "Файл" : "File",
    sourceCode: ua ? "Код" : "Source code",
    config: ua ? "Конфіг" : "Config",
    documentation: ua ? "Документація" : "Documentation",
    metadataFile: ua ? "Метадані" : "Metadata",
    asset: "Asset",
    scene: ua ? "Сцена" : "Scene",
    prefab: "Prefab",
    resource: ua ? "Ресурс" : "Resource",
    localization: ua ? "Локалізація" : "Localization",
    environment: "Environment",
    projectConfig: "Project config",
    productConfig: "Product config",
    relationshipMap: ua ? "Зв’язки" : "Relationships",
    pipeline: "Pipeline",
    test: "Test",
    other: ua ? "Інше" : "Other",
    relationships: ua ? "Зв’язки файлів" : "File relationships",
    uses: ua ? "Використовує" : "Uses",
    usedBy: ua ? "Використовується в:" : "Used in:",
    manages: ua ? "Керує" : "Manages",
    directChildren: ua ? "прямих" : "direct",
    nestedFiles: ua ? "файлів усередині" : "files nested",
  };
}

function displayRunMode(mode?: string): string {
  if (mode === "commercial") return "GPT";
  if (mode === "hf-open") return "Qwen";
  if (mode === "hybrid") return "Hybrid";
  return "Baseline";
}

function formatDate(value?: string, language: "ua" | "en" = "en"): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return `${date.toLocaleString(language === "ua" ? "uk-UA" : "en-GB", {
    timeZone: "UTC",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  })} UTC`;
}

export function RunDetailsPanel({
  details,
  loading,
  error,
  language = "en",
  labels,
}: RunDetailsPanelProps) {
  const isUa = language === "ua";
  const text = {
    empty: isUa
      ? "Обери запуск, щоб переглянути деталі."
      : "Select a run to inspect it.",
    loading: isUa ? "Завантажуємо деталі запуску..." : "Loading run details...",
    title: "Run Details",
    summary: isUa ? "Підсумок" : "Summary",
    modules: isUa ? "Обрані модулі" : "Selected modules",
    metrics: isUa ? "Метрики" : "Metrics",
    advanced: isUa ? "Розширені metadata" : "Advanced metadata",
    platform: isUa ? "Платформа" : "Platform",
    mode: isUa ? "Режим" : "Mode",
    provider: isUa ? "Провайдер" : "Provider",
    created: isUa ? "Створено" : "Created",
    architecture: isUa ? "Архітектура" : "Architecture",
    state: "State",
    navigation: isUa ? "Навігація" : "Navigation",
    zip: "ZIP",
    ready: isUa ? "готовий" : "ready",
    missing: isUa ? "відсутній" : "missing",
    files: isUa ? "файлів" : "files",
    artifacts: isUa ? "блоків плану" : "plan blocks",
    warnings: isUa ? "попереджень" : "warnings",
    validation: isUa ? "перевірка" : "validation",
    advisorTitle: isUa ? "Пояснення advisor-а" : "Advisor explanation",
    advisorRationale: isUa ? "Архітектурне рішення" : "Architecture rationale",
    advisorModules: isUa ? "Вплив модулів" : "Module impact",
    advisorMode: isUa ? "Роль режиму генерації" : "Generation mode impact",
    advisorTradeoffs: isUa ? "Компроміси" : "Trade-offs",
    advisorChecks: isUa ? "Наступні перевірки" : "Next checks",
    relationshipEdges: isUa ? "Зв’язки" : "Relations",
    aiContribution: isUa ? "Внесок AI" : "AI contribution",
    projectTree: isUa ? "Дерево цього запуску" : "This run file tree",
    ...labels,
  };

  if (loading) return <div className="empty-state">{text.loading}</div>;
  if (error) return <div className="empty-state error-muted">{error}</div>;
  if (!details)
    return text.empty ? <div className="empty-state">{text.empty}</div> : null;

  const metrics = details.metrics;
  const spec = details.spec;
  const modules =
    spec?.modules
      .filter((module) => module.enabled)
      .map((module) => module.featureId) ?? [];
  const validationStatus =
    details.validationV2?.postMaterialization?.status ??
    details.validationV2?.preMaterialization?.status ??
    details.validation?.status ??
    "-";
  const mode = displayRunMode(details.metadata.generationMode ?? "baseline");
  const synthesisProvider = details.architectureSynthesis?.usedAi
    ? `${details.architectureSynthesis.provider}${details.architectureSynthesis.model ? ` · ${details.architectureSynthesis.model}` : ""}`
    : "deterministic";
  const hybridProvider =
    details.hybridRefinement?.provider &&
    details.hybridRefinement.provider !== "deterministic"
      ? `${details.hybridRefinement.provider}${details.hybridRefinement.model ? ` · ${details.hybridRefinement.model}` : ""}`
      : undefined;
  const provider =
    details.metadata.generationMode === "hybrid" && hybridProvider
      ? `deterministic base + ${hybridProvider} refinement`
      : synthesisProvider;
  const fileCount =
    metrics?.fileCount ??
    details.metadata.fileTree?.filter((node) => node.type === "file").length ??
    "-";
  const relationCount =
    details.relationshipGraph?.summary?.edges ??
    details.artifacts.filter((artifact) =>
      artifact.path.includes("relationship"),
    ).length;
  const humanSummary = isUa
    ? `${details.metadata.projectName} · ${mode} · ${details.metadata.profile} · ${fileCount} ${text.files} · ${text.validation}: ${validationStatus}.`
    : `${details.metadata.projectName} · ${mode} · ${details.metadata.profile} · ${fileCount} ${text.files} · ${text.validation}: ${validationStatus}.`;
  const modulePreview = modules.slice(0, 8).join(", ") || "core";
  const synthesis = details.architectureSynthesis;
  const hybrid = details.hybridRefinement;
  const synthesisSignals = [
    ...(synthesis?.assumptions ?? []),
    ...(synthesis?.recommendations ?? []),
    ...(synthesis?.risks ?? []),
  ].filter(Boolean);
  const aiContributionBody =
    details.metadata.generationMode === "hybrid"
      ? isUa
        ? `Hybrid зберігає обрану користувачем базову архітектуру, але може приймати AI-refinement patches для глибини файлів, readiness, relationships і пояснень. Прийнято patches: ${hybrid?.acceptedPatches?.length ?? 0}, відхилено: ${hybrid?.rejectedPatches?.length ?? 0}.`
        : `Hybrid keeps the user-selected base architecture, but may accept AI refinement patches for file depth, readiness, relationships and explanations. Accepted patches: ${hybrid?.acceptedPatches?.length ?? 0}, rejected: ${hybrid?.rejectedPatches?.length ?? 0}.`
      : details.architectureSynthesis?.usedAi
        ? isUa
          ? `${mode} вплинув на деталізацію дерева, naming, relationship-рішення, ризики та рекомендації без самовільної зміни вибраних перемикачів архітектури. AI-сигналів у metadata: ${synthesisSignals.length}.`
          : `${mode} influenced file-tree depth, naming, relationship decisions, risks and recommendations without overriding selected architecture switches. AI signals in metadata: ${synthesisSignals.length}.`
        : isUa
          ? "Baseline є контрольним запуском: дерево будується deterministic-правилами без AI-рішень, щоб було з чим порівнювати GPT, Qwen і Hybrid."
          : "Baseline is the control run: the tree is built by deterministic rules without AI decisions, so GPT, Qwen and Hybrid can be compared against it.";
  const advisorBlocks = [
    {
      title: text.advisorRationale,
      body:
        details.advisor?.summary ??
        (isUa
          ? `${details.metadata.profile} starter побудовано навколо ${spec?.architecture.style ?? "обраної"} архітектури, State ${spec?.architecture.stateManagement ?? "default"} і навігації ${spec?.architecture.navigationStyle ?? "default"}.`
          : `${details.metadata.profile} starter uses ${spec?.architecture.style ?? "selected"} architecture with ${spec?.architecture.stateManagement ?? "default"} state and ${spec?.architecture.navigationStyle ?? "default"} navigation.`),
    },
    {
      title: text.advisorModules,
      body: isUa
        ? `Увімкнені модулі (${modulePreview}) представлені service/state/resource/integration boundaries, а не одиночними placeholder-файлами.`
        : `Enabled modules (${modulePreview}) are represented as service, state, resource and integration boundaries instead of isolated placeholder files.`,
    },
    {
      title: text.advisorMode,
      body: details.architectureSynthesis?.usedAi
        ? isUa
          ? `${mode} використав ${provider} як AI-blueprint поверх однакового benchmark-контракту: користувацькі вибори залишаються рамкою, а AI деталізує дерево, ролі файлів, ризики і рекомендації.`
          : `${mode} used ${provider} as an AI blueprint over the same benchmark contract: user choices stay as the frame, while AI expands the tree, file roles, risks and recommendations.`
        : isUa
          ? "Baseline тримає ArchitectureSpec повністю deterministic і працює як контрольна точка для порівняння."
          : "Baseline keeps the ArchitectureSpec fully deterministic and works as the comparison control point.",
    },
    {
      title: text.aiContribution,
      body: aiContributionBody,
    },
    {
      title: text.advisorTradeoffs,
      body: isUa
        ? "Це starter-архітектура: вона робить межі, wiring і зв’язки файлів явними, але не замінює production-ready бізнес-логіку."
        : "This is a starter architecture: it makes boundaries, wiring and file relationships explicit, but does not replace production-ready business logic.",
    },
    {
      title: text.advisorChecks,
      body: isUa
        ? `Наступні перевірки: platform setup, реальні endpoints, warnings (${metrics?.warningCount ?? 0}) і relationship graph (${relationCount}) перед реалізацією.`
        : `Next checks: validate platform setup, connect real endpoints, review warnings (${metrics?.warningCount ?? 0}) and inspect the relationship graph (${relationCount}) before implementation.`,
    },
  ];

  const runTree = buildTreeFromArtifacts(details);
  const runArtifacts = artifactSummaries(details);

  return (
    <div className="run-details-panel redesigned-panel">
      <div className="section-head">
        <div>
          <span className="kicker">{text.title}</span>
          <h2>
            {details.metadata.projectName} · {mode} · {details.metadata.profile}
          </h2>
        </div>
        <span className="status-pill">{details.metadata.status}</span>
      </div>

      <p className="human-summary">{humanSummary}</p>

      <div className="detail-grid">
        <span>
          <small>{text.platform}</small>
          <strong>{details.metadata.profile}</strong>
        </span>
        <span>
          <small>{text.mode}</small>
          <strong>{mode}</strong>
        </span>
        <span>
          <small>{text.provider}</small>
          <strong>{provider}</strong>
        </span>
        <span>
          <small>{text.created}</small>
          <strong>{formatDate(details.metadata.createdAt, language)}</strong>
        </span>
        <span>
          <small>{text.architecture}</small>
          <strong>{spec?.architecture.style ?? "-"}</strong>
        </span>
        <span>
          <small>{text.state}</small>
          <strong>{spec?.architecture.stateManagement ?? "-"}</strong>
        </span>
        <span>
          <small>{text.navigation}</small>
          <strong>{spec?.architecture.navigationStyle ?? "-"}</strong>
        </span>
        <span>
          <small>{text.zip}</small>
          <strong>
            {details.metadata.zipPath ? text.ready : text.missing}
          </strong>
        </span>
      </div>

      <div className="metric-bars">
        <div>
          <span>
            {metrics?.fileCount ?? 0} {text.files}
          </span>
          <i
            style={{
              width: `${Math.min(100, ((metrics?.fileCount ?? 0) / 260) * 100)}%`,
            }}
          />
        </div>
        <div>
          <span>
            {metrics?.artifactCount ?? 0} {text.artifacts}
          </span>
          <i
            style={{
              width: `${Math.min(100, ((metrics?.artifactCount ?? 0) / 90) * 100)}%`,
            }}
          />
        </div>
        <div>
          <span>
            {relationCount} {text.relationshipEdges}
          </span>
          <i
            style={{ width: `${Math.min(100, (relationCount / 520) * 100)}%` }}
          />
        </div>
        <div>
          <span>
            {metrics?.warningCount ?? 0} {text.warnings}
          </span>
          <i
            className="warn-bar"
            style={{
              width: `${Math.min(100, ((metrics?.warningCount ?? 0) / 12) * 100)}%`,
            }}
          />
        </div>
        <div>
          <span>{formatMs(metrics?.generationTimeMs)}</span>
          <i
            style={{
              width: `${Math.min(100, ((metrics?.generationTimeMs ?? 0) / 20000) * 100)}%`,
            }}
          />
        </div>
      </div>

      {modules.length > 0 ? (
        <div>
          <h3>{text.modules}</h3>
          <div className="chip-row">
            {modules.map((module) => (
              <span className="chip" key={module}>
                {module}
              </span>
            ))}
          </div>
        </div>
      ) : null}

      <div className="advisor-summary-card run-advisor-card">
        <h3>{text.advisorTitle}</h3>
        <div className="advisor-grid">
          {advisorBlocks.map((block) => (
            <article key={block.title}>
              <strong>{block.title}</strong>
              <p>{block.body}</p>
            </article>
          ))}
        </div>
      </div>

      {runTree.length > 0 ? (
        <div className="run-details-tree-block">
          <div className="section-head compact-head">
            <div>
              <span className="kicker">{text.projectTree}</span>
              <h3>{details.metadata.projectName}</h3>
            </div>
          </div>
          <FileTreeViewer
            nodes={runTree}
            artifacts={runArtifacts}
            relationshipGraph={details.relationshipGraph}
            language={language}
            labels={fileTreeLabels(language)}
          />
        </div>
      ) : null}

      <details className="advanced-details">
        <summary>{text.advanced}</summary>
        <pre>
          {JSON.stringify(
            {
              synthesis: details.architectureSynthesis,
              validation: details.validationV2,
              relationshipGraph: details.relationshipGraph?.summary,
              metrics,
              advisorStatus: details.advisor?.status,
              hybrid: details.hybridRefinement,
            },
            null,
            2,
          )}
        </pre>
      </details>
    </div>
  );
}
