# ${display_name}

Generated by the Intelligent Mobile Architecture Generator.

## Generated profile
- Profile: ${profile_id}
- Project name: ${project_name}
- Package / Bundle ID: ${package_id}
- Architecture style: ${architecture_style}
- Navigation style: ${navigation_style}
- State management: ${state_management}
- Environment mode: ${environment_mode}
- Entry point: ${entry_point}
- Platform pack: ${platform_pack_label}

## What is included
- entry point
- navigation scaffold
- auth scaffold
- analytics hooks
- localization scaffold
- push placeholders
- networking scaffold
- config / environment files
- state/service layer
- starter example file
- platform pack guide with feature support matrix

## Platform pack baseline

${platform_pack_summary}

### Runtime stack
${platform_pack_dependencies_runtime}

### Development stack
${platform_pack_dependencies_dev}

### Quality gates
${platform_pack_quality_gates}

## Notes
This output is a deterministic scaffold generated from questionnaire answers, rule mappings and template rendering.
Use it as the baseline for extending a real mobile application architecture.
