#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import sys
import zipfile
from pathlib import Path
from string import Template
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent
TEMPLATES_ROOT = ROOT / "templates"
ARTIFACT_REGISTRY_PATH = ROOT.parent.parent / "config" / "artifact-registry.json"


def load_registry() -> List[Dict[str, Any]]:
    parsed = json.loads(ARTIFACT_REGISTRY_PATH.read_text(encoding="utf-8"))
    return parsed if isinstance(parsed, list) else parsed.get("artifacts", [])


def render_template(template_path: Path, context: Dict[str, Any]) -> str:
    raw = template_path.read_text(encoding="utf-8")
    return Template(raw).safe_substitute(flatten_context(context))


def flatten_context(context: Dict[str, Any], prefix: str = "") -> Dict[str, str]:
    flat: Dict[str, str] = {}
    for key, value in context.items():
        target_key = f"{prefix}{key}" if prefix else key
        if isinstance(value, dict):
            flat.update(flatten_context(value, prefix=f"{target_key}_"))
        else:
            flat[target_key] = "" if value is None else str(value)
    return flat


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def substitute_path(template: str, context: Dict[str, Any]) -> str:
    return Template(template).safe_substitute(flatten_context(context))


def profile_output_map(entry: Dict[str, Any], profile: str) -> List[Dict[str, Any]]:
    outputs = entry.get("outputs", {})
    return outputs.get(profile) or outputs.get("default") or []


def write_registry_outputs(
    output_root: Path,
    profile: str,
    artifact_ids: List[str],
    context: Dict[str, Any],
) -> None:
    registry = load_registry()
    entries = {entry["id"]: entry for entry in registry}

    for artifact_id in artifact_ids:
        entry = entries.get(artifact_id)
        if not entry:
            continue
        for output in profile_output_map(entry, profile):
            destination = output_root / substitute_path(output["path"], context)
            ensure_parent(destination)
            if "literal" in output:
                destination.write_text(output["literal"], encoding="utf-8")
                continue
            template_name = output.get("template")
            if not template_name:
                continue
            template_path = TEMPLATES_ROOT / template_name
            destination.write_text(render_template(template_path, context), encoding="utf-8")


def write_metadata_files(output_root: Path, payload: Dict[str, Any]) -> None:
    metadata_root = output_root / ".mag"
    metadata_root.mkdir(parents=True, exist_ok=True)
    (metadata_root / "architecture-spec.json").write_text(
        json.dumps(payload.get("spec", {}), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (metadata_root / "artifact-manifest.json").write_text(
        json.dumps(payload.get("manifest", {}), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (metadata_root / "validation-report.json").write_text(
        json.dumps(payload.get("validation", {}), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (metadata_root / "legacy-plan.json").write_text(
        json.dumps(payload.get("plan", {}), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_profile_specific_stub(output_root: Path, profile: str, context: Dict[str, Any]) -> None:
    project_pascal = context.get("projectPascal", "GeneratedApp")
    if profile == "ios":
        path = output_root / f"{project_pascal}.xcodeproj" / "project.pbxproj"
        ensure_parent(path)
        path.write_text("// Placeholder Xcode project generated by baseline mode\n", encoding="utf-8")
    elif profile == "unity":
        path = output_root / "Assets" / "Scenes" / "SampleScene.unity"
        ensure_parent(path)
        path.write_text("%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n", encoding="utf-8")
    elif profile == "flutter":
        path = output_root / "pubspec.yaml"
        ensure_parent(path)
        path.write_text(
            f"name: {context.get('projectSlug', 'generated_app').replace('-', '_')}\ndescription: Baseline generated starter architecture\nversion: 0.1.0\n",
            encoding="utf-8",
        )
    elif profile == "react-native":
        path = output_root / "package.json"
        ensure_parent(path)
        path.write_text(
            json.dumps(
                {
                    "name": context.get("projectSlug", "generated-app"),
                    "version": "0.1.0",
                    "private": True,
                },
                indent=2,
            ) + "\n",
            encoding="utf-8",
        )


def zip_directory(source_dir: Path, zip_path: Path) -> None:
    ensure_parent(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for file_path in sorted(source_dir.rglob("*")):
            archive.write(file_path, file_path.relative_to(source_dir.parent))


def main() -> int:
    raw = sys.stdin.read().strip()
    if not raw:
        print("Generator payload is empty", file=sys.stderr)
        return 1

    payload = json.loads(raw)
    profile = payload["profile"]
    manifest = payload["manifest"]
    context = payload["templateContext"]
    output_root = Path(payload["outputDir"]) / manifest["rootFolderName"]
    zip_path = Path(payload["zipPath"])

    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    artifact_ids = [artifact["id"] for artifact in manifest.get("artifacts", [])]
    write_registry_outputs(output_root, profile["profile"], artifact_ids, context)
    write_profile_specific_stub(output_root, profile["profile"], context)
    write_metadata_files(output_root, payload)
    zip_directory(output_root, zip_path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
